# Default spring
spring:
  application:
    name: postgresql.tutorial
    
# Jpa
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      org.hibernate.envers.audit_table_suffix: _histo
      org.hibernate.envers.store_data_at_delete: true

# Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/tutorialdb
    username: guestUser
    password: guest
    driver-class-name: org.postgresql.Driver

# Liquibase
liquibase:
  enabled: true
  change-log: classpath:/changelogs/db.changelog-master.xml
  
logging:
  level:
    org:
      hibernate:
        type: trace