# Default spring
spring:
  application:
    name: postgresql.tutorial
    
# Jpa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/tutorialdb
    username: guestUser
    password: guest
    driver-class-name: org.postgresql.Driver

# Liquibase
liquibase:
  enabled: true
  change-log: classpath:/changelogs/db.changelog-master.xml
  
logging:
  level:
    org:
      hibernate:
        type: trace