CREATE TABLE USERS_HISTO (LIKE USERS);
#

ALTER TABLE USERS_HISTO 
	ADD COLUMN rev SERIAL NOT NULL,
	ADD COLUMN revtype smallint;
#

CREATE TABLE TODO_HISTO (LIKE TODO);
#

ALTER TABLE TODO_HISTO	
	ADD COLUMN rev SERIAL NOT NULL,
	ADD COLUMN revtype smallint;
#

CREATE TABLE REVISION (
	revision SERIAL NOT NULL,
    revision_timestamp BIGINT
)
#

CREATE SEQUENCE hibernate_sequence  INCREMENT 1  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1
 #
